def detect_mss(
    structure,
    current_price,
    previous_bias="NEUTRAL",
    structure_breaks=None
):
    """
    Detect Market Structure Shift (MSS).

    MSS is confirmed from an existing structural break.

    Logic:
        BULLISH bias + bearish CHoCH -> BEARISH MSS
        BEARISH bias + bullish CHoCH -> BULLISH MSS

    BOS represents continuation and does not create MSS.

    Parameters
    ----------
    structure : list
        Classified swing structure.

    current_price : float
        Current market price.

    previous_bias : str
        Structural bias before the latest break.

    structure_breaks : list, optional
        Confirmed BOS / CHoCH events generated by SMCEngine.
    """

    # ==================================================
    # VALIDATE CURRENT PRICE
    # ==================================================

    try:
        current_price = float(current_price)

    except (TypeError, ValueError):

        return {
            "status": "ERROR",
            "mss": False,
            "direction": "NEUTRAL",
            "type": None,
            "price": None,
            "broken_level": None,
            "broken_structure": None,
            "reason": "Invalid current price"
        }

    # ==================================================
    # NORMALIZE BIAS
    # ==================================================

    previous_bias = str(
        previous_bias
    ).upper()

    if previous_bias not in {
        "BULLISH",
        "BEARISH",
        "NEUTRAL"
    }:

        previous_bias = "NEUTRAL"

    # ==================================================
    # STRUCTURE BREAKS ARE THE SOURCE OF TRUTH
    # ==================================================

    if isinstance(
        structure_breaks,
        list
    ) and structure_breaks:

        latest_break = structure_breaks[-1]

        if not isinstance(
            latest_break,
            dict
        ):

            return {
                "status": "OK",
                "mss": False,
                "direction": previous_bias,
                "type": None,
                "price": current_price,
                "broken_level": None,
                "broken_structure": None,
                "reason": "Invalid latest structure break"
            }

        break_type = str(
            latest_break.get(
                "type",
                ""
            )
        ).upper()

        break_direction = str(
            latest_break.get(
                "direction",
                ""
            )
        ).upper()

        break_price = latest_break.get(
            "price"
        )

        broken_swing_index = latest_break.get(
            "broken_swing_index"
        )

        # ==================================================
        # BEARISH MSS
        # ==================================================

        if (
            break_type == "CHOCH"
            and
            break_direction == "BEARISH"
            and
            previous_bias == "BULLISH"
        ):

            return {
                "status": "OK",
                "mss": True,
                "direction": "BEARISH",
                "type": "BEARISH_MSS",
                "price": current_price,
                "broken_level": (
                    float(break_price)
                    if break_price is not None
                    else None
                ),
                "broken_structure": "HL",
                "broken_swing_index":
                    broken_swing_index,
                "reason": (
                    "Bearish CHoCH confirmed "
                    "a market structure shift"
                )
            }

        # ==================================================
        # BULLISH MSS
        # ==================================================

        if (
            break_type == "CHOCH"
            and
            break_direction == "BULLISH"
            and
            previous_bias == "BEARISH"
        ):

            return {
                "status": "OK",
                "mss": True,
                "direction": "BULLISH",
                "type": "BULLISH_MSS",
                "price": current_price,
                "broken_level": (
                    float(break_price)
                    if break_price is not None
                    else None
                ),
                "broken_structure": "LH",
                "broken_swing_index":
                    broken_swing_index,
                "reason": (
                    "Bullish CHoCH confirmed "
                    "a market structure shift"
                )
            }

        # ==================================================
        # BOS = CONTINUATION
        # ==================================================

        return {
            "status": "OK",
            "mss": False,
            "direction": break_direction
                if break_direction in {
                    "BULLISH",
                    "BEARISH"
                }
                else previous_bias,
            "type": None,
            "price": current_price,
            "broken_level": None,
            "broken_structure": None,
            "broken_swing_index": None,
            "reason": (
                "Latest structural break "
                "does not represent an MSS"
            )
        }

    # ==================================================
    # FALLBACK
    #
    # Kept for compatibility if MSS is called without
    # structure_breaks.
    # ==================================================

    if not isinstance(
        structure,
        list
    ):

        return {
            "status": "ERROR",
            "mss": False,
            "direction": "NEUTRAL",
            "type": None,
            "price": current_price,
            "broken_level": None,
            "broken_structure": None,
            "reason": "Invalid structure"
        }

    return {
        "status": "OK",
        "mss": False,
        "direction": previous_bias,
        "type": None,
        "price": current_price,
        "broken_level": None,
        "broken_structure": None,
        "broken_swing_index": None,
        "reason": (
            "No confirmed structure break supplied"
        )
    }